source.. = src/main/java
output.. = classes/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               resources/,\
               help/,\
               dist/application/,\
               lib/,\
               doc.zip,\
               about.ini,\
               IusCLFeature32.png,\
               lib/logback-classic-1.6.2.jar,\
               lib/logback-core-1.6.2.jar,\
               lib/packages-design/usr/iuscl-package-usr-design-2.0.0.jar,\
               lib/packages-design/usr/jdom-1.1.2.jar,\
               lib/lombok-1.18.46.jar,\
               lib/slf4j-api-2.0.19.jar,\
               conf/
jars.compile.order = .
