<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.iuscl</groupId>
		<artifactId>iuscl-package-usr-bom</artifactId>
		<version>2.0.0</version>
	</parent>

	<artifactId>iuscl-package-usr-design</artifactId>
	<packaging>jar</packaging>

	<name>IusCL Usr Design Package</name>
	
	<properties>
		<iuscl.plugin.location>${project.basedir}/../../IusCLPlugin/lib/packages-design/usr</iuscl.plugin.location>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>../src/main</directory>
				<includes>
					<include>resources/**/*</include>
				</includes>
			</resource>
			<resource>
				<directory>../package-common</directory>
				<includes>
					<include>META-INF/LICENSE.txt</include>
				</includes>
			</resource>
		</resources>

		<sourceDirectory>../src/main/java</sourceDirectory>

		<plugins>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<archive>
						<manifestEntries>
							<Built-By>Maven from Eclipse</Built-By>
						</manifestEntries>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addClasspath>true</addClasspath>
<!--							<classpathPrefix>lib</classpathPrefix>-->
						</manifest>
					</archive>
					<includes>
						<include>org/**/*</include>
						<include>resources/**/*</include>
						<include>META-INF/LICENSE.txt</include>
					</includes>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.4.0</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<archive>
						<manifestEntries>
							<Built-By>Maven from Eclipse</Built-By>
						</manifestEntries>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
					</archive>
					<excludes>
						<exclude>resources/**/*</exclude>
						<exclude>conf/**/*.properties</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.4.0</version>
				<executions>
					<execution>
						<id>copy-to-plugin</id>
						<phase>install</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${iuscl.plugin.location}</outputDirectory>
							<resources>
								<resource>
									<directory>target</directory>
									<includes>
										<include>iuscl-package-usr-design-2.0.0.jar</include>
										<include>
											iuscl-package-usr-design-2.0.0-sources.jar</include>
									</includes>
								</resource>
								<resource>
									<directory>target/classpath</directory>
									<excludes>
										<exclude>org.eclipse.swt*</exclude>
									</excludes>
								</resource>
								<resource>
									<directory>target/generated-resources</directory>
									<includes>
										<include>licenses/**/*</include>
										<include>licenses.xml</include>
									</includes>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>