source.. = src/main/java,\
               src/main/resources,\
               src/test/java,\
               src/test/resources/
output.. = target/classes/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               help/,\
               dist/application/,\
               doc.zip,\
               about.ini,\
               IusCLFeature32.png,\
               conf/,\
               lib/logback-classic-1.6.4.jar,\
               lib/logback-core-1.6.4.jar,\
               lib/lombok-1.18.46.jar,\
               lib/roaster-api-2.30.3.Final.jar,\
               lib/roaster-jdt-2.30.3.Final.jar,\
               resources/,\
               target/classes/,\
               iuscl-design-packages/iuscl-package-usr-design/iuscl-package-usr-design-2.0.0.jar,\
               iuscl-design-packages/iuscl-package-usr-design/jdom-1.1.2.jar,\
               iuscl-design-packages/iuscl-package-usr-design/slf4j-api-2.0.19.jar,\
               iuscl-design-packages/iuscl-package-pdf-design/itextpdf-5.1.3.jar,\
               iuscl-design-packages/iuscl-package-pdf-design/iuscl-package-pdf-design-2.0.0.jar
jars.compile.order = .
